server:
  port: 8443
  ssl:
    key-store: /sandc.xyz.jks
    key-store-password: d45dev2lvs7
spring:
  jpa:
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/s_c?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: zhanglingzhe0820
